import React, { Suspense, lazy } from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { registerSW } from 'virtual:pwa-register';
import LandingPage from './LandingPage';
import ConceptPage from './ConceptPage';
import { useDocumentMeta } from './lib/useDocumentMeta';
import './i18n';
import './index.css';

// Register the service worker generated by vite-plugin-pwa
registerSW({ immediate: true });

/**
 * Legacy hash-route shim.
 *
 * The app used a HashRouter until the move to real URLs, so links in the wild
 * — LMS embeds especially — point at /#/sim and /#/instructor. A hash never
 * reaches the server, so those URLs would silently land on the home page
 * instead of 404ing, which is the worst kind of breakage: invisible.
 *
 * Rewrite them to the equivalent path before React mounts. Runs once, guarded
 * so it cannot loop.
 */
if (typeof window !== 'undefined' && window.location.hash.startsWith('#/')) {
  const target = window.location.hash.slice(1);
  window.history.replaceState(null, '', target + window.location.search);
}

const App = lazy(() => import('./App'));
const InstructorDashboard = lazy(() => import('./pages/InstructorDashboard'));

const SimFallback = (
  <div className="h-screen bg-sim-bg flex items-center justify-center text-white text-lg">
    Loading simulator…
  </div>
);

/**
 * Meta wrappers for the lazy routes.
 *
 * Without these, /sim and /instructor keep whatever <head> index.html shipped —
 * which means they declare the home page's title AND its canonical, telling
 * search engines they are duplicates of the home page. Wrapping here keeps the
 * simulator and dashboard components free of routing concerns.
 */
function SimRoute() {
  useDocumentMeta({
    title: 'SedSim — Pharmacokinetic Sedation Simulator | The Quantum Distillery',
    description:
      'High-fidelity anesthesia and sedation simulator with real-time vital sign modeling, a pharmacokinetic engine, and an AI clinical mentor. Built for oral surgery training.',
    path: '/sim',
  });
  return <Suspense fallback={SimFallback}><App /></Suspense>;
}

function InstructorRoute() {
  useDocumentMeta({
    title: 'Instructor Dashboard — SedSim',
    description: 'Instructor tooling for SedSim sessions.',
    path: '/instructor',
    noindex: true,
  });
  return <Suspense fallback={SimFallback}><InstructorDashboard /></Suspense>;
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<LandingPage />} />
        <Route path="/concepts/:slug" element={<ConceptPage />} />
        <Route path="/sim" element={<SimRoute />} />
        <Route path="/instructor" element={<InstructorRoute />} />
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
    </BrowserRouter>
  </React.StrictMode>,
);
